version: "3.9"
services:
  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    command: ["air"]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  elasticsearch-admin:
    image: stephanediondev/elasticsearch-admin
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SECRET_REGISTER=goes
  frontend:
    build:
      context: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3001:3001
    volumes:
      - node_modules:/app/node_modules
      - parcel_cache:/app/.parcel-cache
      - yarn_cache:/usr/local/share/.cache/yarn/v6
      - ./frontend:/app
    command: ["yarn", "start"]

volumes:
  esdata:
  node_modules:
  parcel_cache:
  yarn_cache:
