version: '3.9'
services:
  backend:
    build:
      context: .
    depends_on:
      - elasticsearch
    ports:
      - 3000:3000
    environment:
      GOPATH: /go
    volumes:
      - .:/app
      - go:/go
    command: ["fresh"]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
  go:
